### ISSUE TITLE
Node 20 support

### ISSUE THREAD

**Issue by cviebrock** [mheap/phpunit-matcher-action#21]
Actions I have that use this package are showing the following warning (emphasis mine):

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3, **mheap/phpunit-matcher-action@v1**. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Any chance of updating your package?

**Comment by mheap** [comment]
All updated!
