### ISSUE TITLE
Improvement: allow to specify base path

### ISSUE THREAD

**Issue by Xerkus** [mheap/phpunit-matcher-action#9]
I run tests in a docker container built in previous job so teamcity log output has container path instead of github workspace path expected by this action.

I would like to have an option to specify custom base path for the matcher.

**Comment by Xerkus** [comment]
@mheap thanks! can you also tag a release?

**Comment by mheap** [comment]
@Xerkus All done! Your workflows using @v1 will automatically update to use the latest version
